# Generated by Django 2.2.16 on 2026-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_stockholding_bought_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=260)),
                ('asset', models.CharField(blank=True, max_length=120)),
                ('horizon', models.CharField(blank=True, max_length=120)),
                ('price_label', models.CharField(blank=True, max_length=120)),
                ('price_value', models.CharField(blank=True, max_length=80)),
                ('position_note', models.TextField()),
                ('exit_note', models.TextField(blank=True)),
                ('thesis', models.TextField(blank=True)),
                ('guardrails', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=260)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
