# Generated by Django 2.2.16 on 2026-08-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_memonote_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('cash_chf', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bitcoin_chf', models.DecimalField(decimal_places=2, max_digits=18)),
                ('stocks_chf', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bitcoin_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('snapshot_date',),
            },
        ),
    ]
