# Generated by Codex on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_portfoliosnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuoteSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange', models.CharField(blank=True, max_length=120)),
                ('market_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='Yahoo Finance', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ticker', 'symbol'),
                'unique_together': {('ticker', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='StockQuoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=40)),
                ('quote_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(default='Yahoo Finance', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('quote_date', 'ticker', 'symbol'),
                'unique_together': {('ticker', 'symbol', 'quote_date')},
            },
        ),
    ]
