# Generated by Django 2.2.16 on 2026-10-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_lock_august_2026_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='CHF', max_length=3)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_flow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('source_filename', models.CharField(blank=True, max_length=240)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.CreateModel(
            name='SpendingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='CHF', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('transaction_number', models.CharField(blank=True, max_length=80)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blog.SpendingStatement')),
            ],
            options={
                'ordering': ('-booking_date', '-id'),
            },
        ),
    ]
