# Generated by Django 2.2.16 on 2026-10-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_spendingstatement_spendingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingtransaction',
            name='category_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='spendingtransaction',
            name='category_source',
            field=models.CharField(default='rules', max_length=24),
        ),
        migrations.AddField(
            model_name='spendingtransaction',
            name='display_description',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
